### ISSUE TITLE
Null-check fix from #93 still contains bug, tries to .Remove(0, 2) from empty string

### ISSUE THREAD

**Issue by asontu** [bartverdonck/Sitecore-Forms-Extensions#101]
We encountered this bug when trying to send an e-mail with tokens. If the field that the token refers to is a list type and no value is selected then the `Aggregate()` returns an empty string. Trying to do `.Remove(0, 2)` throws an exception because 2 is beyond the end of the (empty) string.

I've changed [line 14](https://github.com/bartverdonck/Sitecore-Forms-Extensions/blob/8b0371ba2eb355575ff681305738626105ac8a0f/src/Feature/FormsExtensions/code/Fields/ValueResolvers/StringValueFromStringListInputViewModelReader.cs#L14) to this on our client's production environment to fix it:

```
args.Value = listStringInputViewModel.Value == null ? string.Empty : string.Join(", ", listStringInputViewModel.Value);
```

**Comment by bartverdonck** [comment]
Ok, thanks, I have updated the code with your suggestion.
