### ISSUE TITLE
The form throws a 404 ajax error when there is more than 5 file upload fields on it

### ISSUE THREAD

**Issue by rabehaja** [bartverdonck/Sitecore-Forms-Extensions#102]
**Describe the bug**
When I have more than 5 file upload fields on the form, the form throws a 404 ajax error on post.

**To Reproduce**
1. Create a form with 6 file upload field on it and add as a save action "redirect to a page"
2. Save
3. Create a page, add a form to the page, save and publish
4. Browse to the corresponding page using your CD (www) url
5. Open your developer console
6. Fill all the file upload fields, click submit and verify the network tab of your developer console
7. Notice the erroneous behavior like displayed on the picture 
![image](https://user-images.githubusercontent.com/10972190/102187793-bfedcc00-3eb4-11eb-81cf-43c01de95316.png)

**Expected behavior**
That the form should post regardless of the amount of file upload field on it

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows, MacOSX, 
 - Browser: Firefox, Chrome, Edge, Internet explorer

**Comment by bartverdonck** [comment]
Hi,

Can you check if you are still below the maxAllowedContentLength or increase it?

  <system.webServer>
    <security>
      <requestFiltering>
        <requestLimits maxAllowedContentLength="52428800" /> 
      </requestFiltering>
    </security>
  </system.webServer>

**Comment by rabehaja** [comment]
Hi, 

Max allowed content is set as such **<requestLimits maxAllowedContentLength="524288000" />**

And I've been using a 10 kb file to make the uploads

Loic

**Comment by bartverdonck** [comment]
Hi, 

Can you state the version of the module and the version of sitecore you are using?

Please note that I'm not actively maintaining 2.x versions of the module anymore. However, the source code is available for you to have a look at if you want a quick solution.

Best Regards

**Comment by rabehaja** [comment]
Hi, 

Sitecore 9.1 update 1 and Sitecore forms extensions 2.2

Best Regards

**Comment by bartverdonck** [comment]
Please have a try with the latest 2.x version (2.3.1). The issue might already be resolved in that one.

If this is not an option, you can try just using the jquery.unobtrusive-ajax.js from that latest version and replace that.

**Comment by bartverdonck** [comment]
Closing the issue, due to innactivity.
