### ISSUE TITLE
Past and minimum 18 validators in date form control

### ISSUE THREAD

**Issue by HazemElSherif** [bartverdonck/Sitecore-Forms-Extensions#105]
If I put date control on a form then check "Past Date Validator" and "Minimum Age 18 Validator" then save the form, the form crashes and I won't be able to open it again 
I'm using Sitecore Forms Extensions for Sitecore 9.1-2.3.1 

1. In forms Designer, Create blank form
2. Drag and drop Date control
3. Check "Past Date Validator" and "Minimum Age 18 Validator"
4. Save the form

**Expected behavior**
The form shouldn't save and I should be able to continue editing the form 

**Actual behavior**
The form disappears permanently, If I refresh, the form is still disappeared

**Screenshots**

![Capture](https://user-images.githubusercontent.com/30274696/104847694-5f561280-58ea-11eb-9f59-118d8ffae38f.PNG)

![error](https://user-images.githubusercontent.com/30274696/104848088-0b4c2d80-58ec-11eb-8170-4d5c591efbaf.PNG)

**Comment by bartverdonck** [comment]
Thx for reporting, I will have to checkout in detail.

Meanwhile you can fix you form by removing the validators directly on the items in the content editor.

**Comment by HazemElSherif** [comment]
Any updates on this issue?

**Comment by MatsLindberg** [comment]
Yes wondering the same thing, any ETA when the bug is fixed:)

/Mats

**Comment by bartverdonck** [comment]
Hi, thanks for your interest in SFE. 
I cannot commit to timings on when next version or bugfixes will be released as this is maintained on a pure voluntary basis.

Please note that this module is released in open source, all source code (+setup guide) is available to fix the issue if you cannot wait until the new release.

Kind Regards

**Comment by bartverdonck** [comment]
Issue confirmed

**Comment by bartverdonck** [comment]
Problem is in the validation framework itself. It does not allow having the same validator twice on a single field. (Even though they receive different parameters) The same problem occurs when you for instance try to add 2 regular expression validators on a field.

**Comment by bartverdonck** [comment]
Scoped the validationType of the validators provided by the SFE.
https://cm.sfe.localhost/bugs/bug-105
