### ISSUE TITLE
List Fieldtypes not updated to custom Viewmodel classes

### ISSUE THREAD

**Issue by SchelstraeteRuben** [bartverdonck/Sitecore-Forms-Extensions#106]
**Describe the bug**
I just installed the 3.1 package on Sitecore 9.3 and tested the Valueprovider List support. However, it didn't seem to work. I investigated this and it seems that the List fieldtypes, located under _/sitecore/system/Settings/Forms/Field Types/Lists_ still use the out of the box Sitecore Model Type, while this should be the new custom model types such as _Feature.FormsExtensions.Fields.Bindings.ListWithBindingsViewModel,Feature.FormsExtensions_

I checked the item xml files in the package.zip and this confirms my assumption.

**Comment by bverdonck** [comment]
Hi Ruben, thanks for pointing out. I'll have a look.
How did you install the module, via sitecore package or via containers?

**Comment by SchelstraeteRuben** [comment]
Hi Bart,

Thanks for the quick reply! I installed the module via the sitecore package.

**Comment by bartverdonck** [comment]
Fixed
