### ISSUE TITLE
On some field types the Store back checkbox is not visible.

### ISSUE THREAD

**Issue by SchelstraeteRuben** [bartverdonck/Sitecore-Forms-Extensions#107]
**Describe the bug**
On some field types such as Radiobuttonlist, Email, Date, ... There is no store back checkbox. I believe this prevents the value being saved to Xconnect, right? 

This is the checkbox i'm talking about: 
![image](https://user-images.githubusercontent.com/6652115/105984818-f1a0a800-609a-11eb-88d9-7304cae051f0.png)

Is there any additional configuration necessary to enable this functionality? Or is Sitecore preventing proper store back here? 

I'm using the latest version of the SFE (3.1)

**Comment by bverdonck** [comment]
By default, the value providers in Sitecore only provide read capabilities. For storage you are supposed to write custom submit actions.

The store value is added by SFE and is an additional method on valueproviders to provide a write functionality without submit action. The value providers from SFE support this functionality. On your custom value providers you have to implement the IFieldValueBinder from SFE.

http://onelittlespark.bartverdonck.be/sitecoreformsextentions/3.1/developerdoc/valueproviderstoreback.html

I will have a look, why this checkbox is not present on some of the field types.

**Comment by SchelstraeteRuben** [comment]
Thanks for the clarification Bart. It seems that the "store" method isn't called when this checkbox is not present. I'm not sure about this, but definitely something to check out when you investigate this.

**Comment by SchelstraeteRuben** [comment]
In the meantime, i can confirm that the absence of this checkbox prevent storing the values on form submission.

**Comment by bartverdonck** [comment]
In the core-db, you need to add the "StoreBindingValue" controldefinition on the advanced tab of the property editor settings. Looks like these additions have gone lost in an upgrade of the module. I will re-add them.

**Comment by bartverdonck** [comment]
Added store binding on Checkboxlist, dropdownlist, listbox, radiolist, number, multiline, checkbox and date field

**Comment by rabehaja** [comment]
If you add the StoreBindingValue the fields e.g. the **Single Line Text**:

/sitecore/client/Applications/FormsBuilder/Components/Layouts/PropertyGridForm/PageSettings/Settings/SingleLineText/Advanced

And add in the ControlDefinitions field the StoreBindingValue, you will be able to see the checkbox in the form editor.

P.S: I just downloaded and installed the last package of Forms Extension and still experience this issue.
