### ISSUE TITLE
Bypass recaptcha v2

### ISSUE THREAD

**Issue by druhela** [bartverdonck/Sitecore-Forms-Extensions#108]
Hi

We have test automation tool for testing our website. But we need to get our forms to be tested using this automated tool. So how can we bypass recaptcha successful form submission ?
We are using Sitecore 9.1 and recaptcha v2.

Thanks and Regards
Divya

**Comment by markgibbons25** [comment]
Not sure if it would work but you can enable test mode with these keys https://developers.google.com/recaptcha/docs/faq#id-like-to-run-automated-tests-with-recaptcha.-what-should-i-do

**Comment by bartverdonck** [comment]
Hi Druhela, 

Did Mark's suggestion solve your issue?

Best Regards,

**Comment by bartverdonck** [comment]
Hi Druhela,

I hope Mark's suggestion solved your issue?

I'm going to  close this issue as "bypassing" is out of scope of this module.

Best Regards,
