### ISSUE TITLE
Show Form Page Not Focused on Page after Submit

### ISSUE THREAD

**Issue by everdoorn** [bartverdonck/Sitecore-Forms-Extensions#111]
In Sitecore 9.2 we have added forms to pages, along with other content. Some of the forms are rather lengthy. We are using the Show Form Page submit action to show a thank you message to the user after submitting the form. The thank you page is much shorter than the form itself. The scenario we are seeing is that when you click submit the thank you page is indeed shown but the user has to scroll back up the page to see it. It appears that the page is keeping the scroll position the same after submission and reload, but because the thank you page is so much smaller than the form itself it is bringing all the content from further down the page into view. 

**To Reproduce**

1. Create a form with many fields and sections in a single page so that the content is very long
2. Create a second page with a thank you message 
3. Add the form to a page with content below the form (i.e. an accordion and a footer) 
4. Submit the form 
5. Page 2 of the form will be shown but out of view as the content that was below the form is now brought into view. 

**Expected Result**
The focus should be on the thank you page after form submission

**Screenshots (Content removed from images for security)**
Before the form is submitted
![image](https://user-images.githubusercontent.com/18175738/107605692-8823ac00-6bf9-11eb-983b-67cd8c83f848.png)

View after the form is submitted (thank you message is above the visible screen)
![image](https://user-images.githubusercontent.com/18175738/107605748-abe6f200-6bf9-11eb-8634-d31f6d4603f4.png)

Thank You message after scrolling up on the page
![image](https://user-images.githubusercontent.com/18175738/107605777-c620d000-6bf9-11eb-8528-b1a27f9e3d92.png)

**Desktop**
 - OS: Windows
 - Browser(s): Chrome, Firefox
 - Version: 88.0.4324.150

If a video would help one can be uploaded.

**Comment by bartverdonck** [comment]
Hi,

So, I understand that the issue occurs once the form is larger than the screen size. And basicaly, you would want an anchor that jumps to the top of the form.

I'm afraid that I'm not directly seeing a way for the module to change this default behaviour of Sitecore forms.

What you could do as a work around is adding a "RawHtml" component on you thank you page.
In the component add
`<a id="formTop"></a>
<script>
	location.href="#formTop";
</script>`
or add
`<a id="formTop"></a>
<script>
	document.getElementById("formTop").scrollIntoView()
</script>`

When this page is shown, the javascript will execute and jump to the correct place.

Best Regards,

Bart

**Comment by bartverdonck** [comment]
I have added an example in the source-code. https://cm.sfe.localhost/issues/issue-111

**Comment by everdoorn** [comment]
@bartverdonck Thank You
