### ISSUE TITLE
Adding the 'Checkbox List' field results in an error

### ISSUE THREAD

**Issue by HendrikClercx** [bartverdonck/Sitecore-Forms-Extensions#114]
**Version**
Sitecore Forms Extension Version: 3.2.0

**Describe the bug**
Adding the Checkbox List field in Sitecore Forms results in an error. It is currently not possible to use this field. 

The wrong ViewModel is passed to the CheckboxList.cshtml. It expects a Model of type `Sitecore.ExperienceForms.Mvc.Models.Fields.CheckBoxListViewModel`. Instead the `Feature.FormsExtensions.Fields.Bindings.CheckBoxViewWithBindingsTokenModel` is passed in the view. Since this inherits from `CheckBoxViewModel` it throws an exception.

**Logs**
Message: The model item passed into the dictionary is of type 'Feature.FormsExtensions.Fields.Bindings.CheckBoxViewWithBindingsTokenModel', but this dictionary requires a model item of type 'Sitecore.ExperienceForms.Mvc.Models.Fields.CheckBoxListViewModel'.

**To Reproduce**
1. Go to Forms
2. Add Checkbox List

**Expected behavior**
Should be possible to use this field type in Sitecore Forms.

**Solution**
Modify the Checkbox List.yml (https://github.com/bartverdonck/Sitecore-Forms-Extensions/blob/master/src/Feature/FormsExtensions/items/FieldTypeLists/Lists/Checkbox%20List.yml)
and change value to `Feature.FormsExtensions.Fields.Bindings.CheckBoxListWithBindingsViewModel, Feature.FormsExtensions` 

![image](https://user-images.githubusercontent.com/50102259/110662617-f68e6680-81c5-11eb-806f-0f97625bcee6.png)

**Comment by GreyGhostStudio** [comment]
Same issue here.

@HendrikClercx , thx for the detailed fix. Your timing was perfect!!

**Comment by bartverdonck** [comment]
Hi, 
Thanks for the feedback.
I'll try to provide a bugfix asap.
Best Regards

**Comment by jammykam** [comment]
Been staring at this bug for a while and could not for the life of me see that small difference in the name! Thanks for the hint @HendrikClercx. Can confirm this fixed it for me too.

**Comment by bartverdonck** [comment]
Released 3.2.1 and 4.0.1 with fix.

**Comment by jammykam** [comment]
For the sake of consistency (and i realise there is probably no code update to 3.2.1, only updates), will the update be pushed to Nuget?
