### ISSUE TITLE
Uncaught TypeError: Cannot set property 'BindingTarget' on Sitecore 10.1

### ISSUE THREAD

**Issue by codywatkins** [bartverdonck/Sitecore-Forms-Extensions#118]
Using the latest version of Forms Extensions on a Sitecore XM install (understand not all features will work since it's not XP). Mainly wanted the Recaptcha field.

After installing the module, I couldn't add a Send Email action to the submit button, I'd get a blank email modal screen and this JS error below:

![image](https://user-images.githubusercontent.com/3009994/113328843-ab9dd580-92d1-11eb-9386-e718018302e4.png)

**Comment by bartverdonck** [comment]
Hi,

I have retested this with Sitecore 10.1 XP and everything seems to work fine.

Currently the module is not compatible with Sitecore 10 XM, I will close this issue, as there is already another ticket to make it compatible with XM.  #94 

Best Regards
