### ISSUE TITLE
Allow custom value for hidden field

### ISSUE THREAD

**Issue by DeathAngelDaemon** [bartverdonck/Sitecore-Forms-Extensions#17]
Hello,

I just want to add my thoughts about an enhancement for the hidden field.

**Is your feature request related to a problem? Please describe.**
At the moment I can only select one of the xDB bindings as a source. But there is no simple value field to insert a custom text (or a Sitecore Item ID or something else) as a value for the hidden field.

**Describe the solution you'd like**
I would like to have an additional text field (called "Value" maybe) to add custom text there which is then rendered in the value attribute of the hidden input field. This would give more flexibility to the field and would allow us to use different kind of values I might want (or need) to process in a custom save action.

What do you think about it?

Best regards,
Anna

**Comment by bartverdonck** [comment]
Hi Anna,

Thanks for the suggestion.

Will put it in next version.

Best Regards,
Bart

**Comment by DeathAngelDaemon** [comment]
Hi Bart,

great, thanks!
Looking forward to the new version.

Best regards.
Anna

**Comment by rolek** [comment]
@DeathAngelDaemon I updated the hidden field to support arbitrary values. Please see my fork, "updates" branch. When I am done with my changes, I may create a PR for this one.

**Comment by bartverdonck** [comment]
pull request merged
