### ISSUE TITLE
jQuery script error on submit (IE11/Edge)

### ISSUE THREAD

**Issue by DeathAngelDaemon** [bartverdonck/Sitecore-Forms-Extensions#19]
**Describe the bug**
When clicking on the submit button (no matter whether or which submit action is attached) a javascript error occurs in the Internet Explorer and Microsoft Edge browser. The following message is shown in the console of the developer tools:

`SCRIPT438: Object doesn't support property or method 'has'` in jquery.unobtrusive-ajax.min.js (1,2917)

**To Reproduce**
1. Use a Sitecore instance with this module installed
2. create a form with a submit button (no need to assign any submit action)
3. insert the form into a page
4. open the page in IE or Edge and open the developer tools console
5. click on the submit button and see the error message in the console

**Expected behavior**
Like in any other browser: acting like a form. Reload of the page or execution of any assigned submit action for example.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Internet Explorer 11 or Microsoft Edge

Thanks in advance for your help.
Anna

**Comment by bartverdonck** [comment]
updated javascript to support ie11

**Comment by DeathAngelDaemon** [comment]
It works!
Thanks for fixing.
