### ISSUE TITLE
File Upload: an item with the same key has already been added

### ISSUE THREAD

**Issue by alessiomantegna** [bartverdonck/Sitecore-Forms-Extensions#21]
Hi Bart,

I installed Sitecore Forms Extensions (last version) to use File Upload. 
I created a form and an action to send email to user with attachment. 
The problem is that when I try to attach a document and I click on "send button", email is not sent and and the following error is showed in browser console: 

An item with the same key has already been added. 
Exception Details: System.ArgumentException: An item with the same key has already been added.

Source Error: 
Line 4:  
Line 5:  @{
**Line 6:      using (Html.BeginRenderRouteForm(Model, IsPost))**    
Line 7:      {
Line 8:          @Html.AntiForgeryToken()

Source File: d:\home\site\wwwroot\Views\FormBuilder\Form.cshtml    Line: 6 

 

If document is not attached there is not error and email is sent.
Have you an idea about the problem?
Thanks
Best regards,
Alessio

**Comment by alessiomantegna** [comment]
Hi Bart,
I need to create a "file upload" field without using EXM but using a send
action of "Sitecore 9 Forms - Send Email Action-1.0" package which was
installed in our sitecore project. Have you a guide or an idea to do this?

Thanks

Alessio

Il giorno mar 11 dic 2018 alle ore 13:24 Bart Verdonck <
notifications@github.com> ha scritto:

**Comment by bartverdonck** [comment]
Hi Alessio,

Unfortunately I do not offer support for the Send Email Action module. I can only suggest to look at the source code of both modules and find if you can custom implement something.

May I ask why you are not using EXM? It's available with Sitecore out of the box at no extra charge (if you use your own smtp server. It's a great tool to compose emails.

Best Regards
