### ISSUE TITLE
Package Install Could not load file or assembly 'Microsoft.Data.Services.Client, Version 5.8.1.0'

### ISSUE THREAD

**Issue by lswainsbury** [bartverdonck/Sitecore-Forms-Extensions#22]
**Describe the bug**
Download latest module 1.7, Sitecore package install into Sitecore 9.0.2 (rev. 180604). Install doesn't finish successfully. And then Site continues to return 500 error 'Could not load file or assembly 'Microsoft.Data.Services.Client, Version 5.8.1.0'

**To Reproduce**
1. Sitecore package install into Sitecore 9.0.2 (rev. 180604)
2. Package starts installing
3. After several mins install errors

**Expected behavior**
Install finishes successfully and site loads

**Screenshots**
![image](https://user-images.githubusercontent.com/20478852/49868252-c39d7280-fe04-11e8-967d-3f51577fe8c7.png)

**Desktop (please complete the following information):**
Chrome 70.0.3538.11

**Additional context**
I removed  Microsoft.WindowsAzure.Storage.dll and then the site starts responding

**Comment by bartverdonck** [comment]
The installation works on a fresh Sitecore 9.0.2. There is probably a conflict with your custom solution. You should probably add a dependentAssembly statement in your web.config.

This cannot be provided by the module, as I can't predict every environment this is installed into.

Good luck!
