### ISSUE TITLE
Re-Captcha doesn't seem to work. No server-side validation is triggered

### ISSUE THREAD

**Issue by parcae** [bartverdonck/Sitecore-Forms-Extensions#23]
We installed the Re-captcha module on a Sitecore 9.x Acceptance and Production site, but the service doesn;t seem to work.

Server-side validation doesn't seem to work, because we still get spam messages from the contact-form on the production environment.

If the spambot does a post without the entire CaptchaModel, it seems to be possible to skip the validation that is added in the ReCaptchaValidation attribute. This is also due to the way Sitecore handles the submit of their forms with all the dynamic components.

**Comment by bartverdonck** [comment]
Thanks for reporting. I will put it on the backlog as a bug.

**Comment by bartverdonck** [comment]
Fixed the issue in version 1.8 and version 2.1 to support both Sitecore 9.0.x and 9.1
