### ISSUE TITLE
No multiple ReCaptcha on one page

### ISSUE THREAD

**Issue by DeathAngelDaemon** [bartverdonck/Sitecore-Forms-Extensions#24]
Hello,

it does not seem to be possible to use more then one ReCaptcha on a page: in the case I have two or more forms (each with a captcha) implemented on one page.

When I have this case I get a JS error in the developer tools console:

```
Error: reCAPTCHA has already been rendered in this element recaptcha__en.js:508:380
	N1 https://www.gstatic.com/recaptcha/api2/v1547447582668/recaptcha__en.js:508:380
	onloadCallback https://sitecore-web-qa.pcw.local/en-lu/formstest:260:9
	rh https://www.gstatic.com/recaptcha/api2/v1547447582668/recaptcha__en.js:502:513
	t https://www.gstatic.com/recaptcha/api2/v1547447582668/recaptcha__en.js:499:136
```

Google provides a way to render more than one ReCaptcha on a page. I've found this solution:
https://stackoverflow.com/a/28126317
which also leads to the Google ReCaptcha docs:
https://developers.google.com/recaptcha/docs/display#explicit_render

I know this is not really related to your module but maybe you could fix it?

Best regards
Anna

**Comment by bartverdonck** [comment]
Done.
