### ISSUE TITLE
Hidden field definition does not inherit proper sections

### ISSUE THREAD

**Issue by rolek** [bartverdonck/Sitecore-Forms-Extensions#26]
Currently for 9.1 field value providers cannot be used with any field because field definition does not inherit Value Provider Settings template.

See picture:
![image](https://user-images.githubusercontent.com/589162/52978660-73f09f80-338f-11e9-9471-cdb5990e57f1.png)

**Comment by bartverdonck** [comment]
Ok, thanks for the feedback. Will update this for next release.

**Comment by bartverdonck** [comment]
Fixed in 2.1
