### ISSUE TITLE
Text Fields

### ISSUE THREAD

**Issue by somnathdasda** [bartverdonck/Sitecore-Forms-Extensions#27]
If a predefined text box is used in the form then it is not coming in the UI

**Comment by bartverdonck** [comment]
Could you please elaborate on this issue? It is not clear to me.

Please add:
- Sitecore Version Number
- Module Version Number
- Reproducable Scenario
- Screenshots

Best Regards,

Bart

**Comment by bartverdonck** [comment]
@somnathdasda 
Hi, can you please answer my question regarding further information?
