### ISSUE TITLE
Decode ASCII encoded characters when including form fields in emails

### ISSUE THREAD

**Issue by Balfuset** [bartverdonck/Sitecore-Forms-Extensions#29]
**Is your feature request related to a problem? Please describe.**
I am working on a form that sends an email via EXM including all the formFields in the message body. One such field is a cost, with uesers expected to enter data of the form  £X, including the currency symbole (i.e. £10000). When the field is placed into the email body via the token in EXM the £ sign is covnerted to it's ASCII encoding, so instead of seeing £10000 I see &#163;10000

**Describe the solution you'd like**
For any character that need to be encoded for form submission to be decoded when asssigned to the EXM token for display in email bodies

**Comment by bartverdonck** [comment]
![image](https://user-images.githubusercontent.com/5012835/56854133-0bdfac00-6932-11e9-9019-766cd68cb029.png)
I cannot reproduce this.
