### ISSUE TITLE
Does Not Work On Multi-Page Forms

### ISSUE THREAD

**Issue by tosberg** [bartverdonck/Sitecore-Forms-Extensions#3]
BUG DESCRIPTION:
@bartverdonck 
If you have a multi-page form, then hitting 'Next' does not display the next page.  The first page is refreshed with empty values in the inputs.  I have been able to reproduce this behavior on a FRESH installation of Sitecore 9 update-1 after installing the Sitecore Forms Extensions.

1. Create a multi-page form with two pages.  The first page can simply be any input with a 'Submit' button - it doesn't even have to be any of the custom controls in the extension.
2. The 'Submit' button's navigation step should be 'Next'
3. Actions for the the submit button should be to save the data
4. The 2nd page can simply have a 'Text' field that says 'Thank-you.  Your submission has been recieved'
5. Add the form to a page 
6. Load the page, fill in the inputs on the page and submit
7. You'll see that the form does not display the 2nd - or 'Thank-You' page.  All that displays is the first page, refreshed with no data in the input fields anymore.   I believe the issue is with the 'jquery.unobtrusive-ajax.min.js' file.  However, the data itself IS saved for the form.

When I use the default 'jquery.unobtrusive-ajax.min.js' file that came with the Sitecore 9 Forms then the page being sent back is the 2nd - and correct - page.  In your modified js file, I'm guessing it has something to do with the data being sent as 'multipart/form-data' instead of 'x-www-form-urlencoded'.  When being sent as 'multipart/form-data', it looks like the page data being sent back from the default controller is still the first page so this may be a controller issue instead.

Of course, we can't use the original js file because then the Sitecore-Forms-Extensions don't work properly.  However, if we use your modified version then multi-page forms don't work at all.

**Expected behavior**
I expect the behavior to display the next page.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome (Version 67.0.3396.99 (Official Build) (64-bit))

**Comment by bartverdonck** [comment]
Thanks for the feedback and description @tosberg .

**Comment by bartverdonck** [comment]
Issue has been identified. It has to do with the value that is send through when clicking on the button. A hidden field is send along with it on the same key representing the navigationtype (0=submit, 1=next, -1 = previous). In the original version of the jquery.unobtrusive-ajax.min.js, when the data is send over x-www-form-urlencoded, the value of the button is send first followed by the hidden value. In the modified version over multipart/form, this was inversed resulting in the binding to the formdata model being incorrect.

I have updated the jquery.unobtrusive-ajax.min.js to inverse the values.

**Comment by tosberg** [comment]
Bart = HERO.  Thanks!

**Comment by bartverdonck** [comment]
V1.4.2 released
