### ISSUE TITLE
Date validation min/max 

### ISSUE THREAD

**Issue by floyson-reference** [bartverdonck/Sitecore-Forms-Extensions#30]
The min/max validation on date does not work 100% correct. If you have a validation for example min 18 years old. First the difference in years is calculated between the given date and today. If the birthday is not passed 1 year should be decreased. 
The problem is that in formsextensions.validate.js (getYears(date)) => the date (=string) is compared with temp (=date).

Ex: (tested on 7/3/2019)
![image](https://user-images.githubusercontent.com/42807373/53946704-93443800-40c4-11e9-949d-089899b77a28.png)
![image](https://user-images.githubusercontent.com/42807373/53946712-98a18280-40c4-11e9-9e81-b2ebc30ef829.png)

**Comment by bartverdonck** [comment]
Fixed with help of @floyson-reference
