### ISSUE TITLE
Allow for $(dataFolder) in the rootStoragePath

### ISSUE THREAD

**Issue by RizziFrank** [bartverdonck/Sitecore-Forms-Extensions#31]
**Is your feature request related to a problem? Please describe.**
Wanted to save the uploaded file in within the Sitecore's data folder. 

**Describe the solution you'd like**
 My code is the same as the original, but I just replaced the token:
			var dataFolder = Path.IsPathRooted(Sitecore.Configuration.Settings.DataFolder) ? Sitecore.Configuration.Settings.DataFolder : HttpContext.Current.Server.MapPath(Sitecore.Configuration.Settings.DataFolder);
			RootStoragePath = RootStoragePath.Replace("$(dataFolder)", dataFolder);

But I'm sure there's a better place this should go.

**Describe alternatives you've considered**
I created a custom provider, but it'd be nice for others if it was out of the box.

**Comment by bartverdonck** [comment]
Added relative datafolder support to FileSystemFileUploadStorageProvider
