### ISSUE TITLE
Serialization error while we are trying to submit form from CD servers hosted in Azure web apps

### ISSUE THREAD

**Issue by sreekrishnanks** [bartverdonck/Sitecore-Forms-Extensions#32]
**Describe the bug**
Sitecore throws a System.Runtime.Serialization.SerializationException when clicking on submit action on the forms created using Forms Extensions in the website hosted in Azure Web apps.
Its working in local environment. The issue occurs only when there is shared session state available - in CD servers hosted in Azure Web apps

**To Reproduce**
1. Create a form with a submit action
2. Click on Submit
3. The form stays on the same page, no action is done.
4. See the serialization exception error in the Network tab

**Expected behavior**
The Submit action should work as expected

**Screenshots**
![Serialization exception sitecore forms](https://user-images.githubusercontent.com/8579902/54068062-19e84900-426e-11e9-86e4-d02f3dc146e6.png)

**Desktop (please complete the following information):**
 - OS: NA 
 - Browser Chrome
 - Version 72.0.3626.121

**Comment by bartverdonck** [comment]
Based on the sitecore.kernel version in the epic, I assume this is for Sitecore 9.0

**Comment by bartverdonck** [comment]
@sreekrishnanks 
I am not able to reproduce this issue. Can you provide more details regarding your form? What kind of fields are you using?

**Comment by bartverdonck** [comment]
@sreekrishnanks 
Please provide full stacktrace, I cannot find anything wrong with the module.

Best Regards,
Bart
