### ISSUE TITLE
Show Form Page and Language Versions

### ISSUE THREAD

**Issue by pmparis** [bartverdonck/Sitecore-Forms-Extensions#34]
**Second Page shows default language.**

I am a form created in 2 languages.  
English
Japanese

Page 1  - English/Japanese
Page 2 - English/Japanese

When I browsing the site in the Japanese language, The first page shows correctly in Japanese.  When I click submit, the second page shows, but shows the english version and not the Japanese version.    

I did see that there was another ticket about this.  I am not sure what the resolution was however.  Language sites are working perfectly otherwise, so I am not sure what the issue is here. 

Thanks.

**Comment by bartverdonck** [comment]
I have tried this on Sitecore 9.1 and 9.11.

Could not reproduce the issue.
