### ISSUE TITLE
Send to form field value gets not extracted from DropDownList

### ISSUE THREAD

**Issue by InverterOfControl** [bartverdonck/Sitecore-Forms-Extensions#35]
**Describe the bug**
When we set the Submit-Action to *SendMail* and use the feature to use a *value from a field* in this form the *FieldValueContactIdentierHandler.cs* tries to get the value from the dropdown but the string returned from the *GetValue*-method contains the type of the field and not the value.

**To Reproduce**
1. Add a dropdown to a Sitecore Form
2. For the List Items choose *Dynamic* and select a suitable datasource
3. Set Value Field and Text Field accordingly (our Value field is the field that contains the e-mail-address)
4. Add a submit-button and add an action *Send Email*
5. In the dialog set *Mail to* to *Value from field in this form*
6. set *Email Field* to the dropdown created earlier
7. put the form on a page, fill it out and submit

**Expected behavior**
When the form is submitted an email should be send to the selected dropdown-value.

**Screenshots**
The following error message appears in the log:
![image](https://user-images.githubusercontent.com/12115907/56046589-dd63ad80-5d43-11e9-82cc-392f51c70b35.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome

**Additional context**
I added an additional if-clause to solve this particular issue. Do you accept pull-requests?

**Comment by bartverdonck** [comment]
Added fix to support multivalue fields like droplist.
