### ISSUE TITLE
Conditions not working with hidden field.

### ISSUE THREAD

**Issue by rolek** [bartverdonck/Sitecore-Forms-Extensions#36]
**Describe the bug**
Edit conditions modal dialog does not render any operators for the hidden field.

**To Reproduce**
1. Add hidden field to the form
2. Set or not set any value provider for the field (also, unable to set default value, it is not saved)
3. Add section.
4. Edit section condition (the one from point 3)
5. Choose hidden field (from step 1 in the IF - first drop down. Second dropdown is empty.
**Expected behavior**
Point 5: second drop down should have operators available

**Screenshots**
![image](https://user-images.githubusercontent.com/589162/56372655-a3b7fa00-61bc-11e9-94fe-1fbf37b2014f.png)

**Comment by bartverdonck** [comment]
@rolek 
Thanks for the contribution.
I have merged your pull request into master branch.
