### ISSUE TITLE
Publish a NuGet package

### ISSUE THREAD

**Issue by richardszalay** [bartverdonck/Sitecore-Forms-Extensions#38]
Defining custom bindings requires implementing the `IBindingHandler` type but, since there is no NuGet package for the project, the only way to do this is to copy the assembly into the project or publish a custom NuGet package to a private feed.

Any chance we can get an official NuGet package to make this process a little easier?

**Comment by markgibbons25** [comment]
+1, use case here is extending SendEmailExtended with some custom client logic

**Comment by bartverdonck** [comment]
Sorry it took some time, but here it is!
https://www.nuget.org/packages/SitecoreFormsExtensions.Core/
