### ISSUE TITLE
Google Captcha javascript error in form editor

### ISSUE THREAD

**Issue by abhaydhar** [bartverdonck/Sitecore-Forms-Extensions#40]
**Describe the bug**
on drag drop the custom recaptcha control on form editor I get the below error on browser console. I checked the JS load order/sequence , which looks correct .
*VM3527:1 Uncaught ReferenceError: reCaptchaArray is not defined*
   *at eval (eval at globalEval (jquery-2.1.1.js:330), <anonymous>:1:1)*
   *at eval (<anonymous>)*

Other details
Sitecore version 9.1.1, SXA 1.8

**Comment by LexRaaphorst** [comment]
I got the same error after updating to 2.2 from 2.1, so I switched back.

**Comment by vaggelis2018** [comment]
Same error here.

**Comment by bartverdonck** [comment]
Was able to reproduce.

**Comment by bartverdonck** [comment]
Fixed in 2.2.1, now available for download
