### ISSUE TITLE
Additional field types are not configured for insert options

### ISSUE THREAD

**Issue by svenkle** [bartverdonck/Sitecore-Forms-Extensions#41]
**Describe the bug**
Additional field types are not configured for insert options

**Screenshots**
![image](https://user-images.githubusercontent.com/3377341/58603808-82771d00-82d5-11e9-947c-ae5d05e3a953.png)

**Comment by bartverdonck** [comment]
Will have a look at this with version 9.3

**Comment by bartverdonck** [comment]
Done in 9.3
