### ISSUE TITLE
Call the Success/Error Page on the click of Submit Button

### ISSUE THREAD

**Issue by prabhatsharmafr** [bartverdonck/Sitecore-Forms-Extensions#44]
Hi, 

I have Newsletter form which consists of an Email field and a Submit Button. I have created a custom Save Action which calls an API and gets the response. Till now the functionality working fine. I have 2 different scenario's when API returns response "A", the form should redirect to Success Page and if API returns response "B", the form should redirect to Error Page.

I don't want to create a Save Action where user can select the Page types (or which Page to redirect), all should be done by the logic written in Save Action file. Also in both scenario's I want to return a URL to Success/Error Page. For Example, the Success Page should look like this:

Thanks for the subscribing.
Follow this URL - {URL} (this URL is directly coming from the API's response)

How to show this URL on both Pages? Or is there any way I can grab the next page to be called in case of Navigation Step of Submit Button set as Next?

Thanks

**Comment by bartverdonck** [comment]
Hi, this doesn't look like a problem with the module. These kind of questions can be asked on Sitecore Stack Exchange (https://sitecore.stackexchange.com/) or on the Sitecore channels in slack.

Hope you will find a solution there.
