### ISSUE TITLE
Wrong config setting for MakeContactKnownOnFormsUpdate

### ISSUE THREAD

**Issue by markgibbons25** [bartverdonck/Sitecore-Forms-Extensions#46]
Setting is reading XDbPreferredAddress instead of MakeContactKnownOnFormsUpdate

https://github.com/bartverdonck/Sitecore-Forms-Extensions/blob/817f45b11590f80079dff731d9e01adda4300666/src/Feature/FormsExtensions/code/XDb/Repository/XDbContactRepository.cs#L59

**Comment by bartverdonck** [comment]
Thanks for the report. Corrected mistake in code.
