### ISSUE TITLE
Support for using session with StateServer or SQLServer

### ISSUE THREAD

**Issue by robingrayson** [bartverdonck/Sitecore-Forms-Extensions#5]
Upon submission of a form, if session is configured to use either StateServer or SQL an exception is thrown due to being unable to serialise the session state.

Stack trace attached.

[stack trace.txt](https://github.com/bartverdonck/Sitecore-Forms-Extensions/files/2166107/stack.trace.txt)

**Comment by robingrayson** [comment]
Just noticed a similar issue fixed with 1.4, will check with that version

**Comment by bartverdonck** [comment]
HI, did you still have the issue with version 1.4.3?

**Comment by robingrayson** [comment]
No - problem is resolved with 1.4.3 thanks!
