### ISSUE TITLE
The jquery.unobtrusive-ajax.js version breaks AJAX form calls

### ISSUE THREAD

**Issue by dnstommy** [bartverdonck/Sitecore-Forms-Extensions#50]
Issue:
When a form is set to AJAX mode, the POST of the form breaks the controller in Mac Chrome because it does not find enough Navigation fields in the form post.

Here is the request in inspector
Windows Chrome
![image](https://user-images.githubusercontent.com/3902020/63799126-689ba500-c8d9-11e9-81cb-5414e971d937.png)

Apple Chrome
![image](https://user-images.githubusercontent.com/3902020/63799140-781aee00-c8d9-11e9-9f97-14663d3cd9a4.png)

Notice there is only 1 `Submit` in the post for Apple chrome. The controller is looking for submit[1] and since there is only one, it throws a null error. 

The only fix for me is to put the Out of the box sitecore JS files back in.

**Comment by bartverdonck** [comment]
Replaced jquery.unobtrusive-ajax.js with new version supporting form/multipart and compatible with Safari.
