### ISSUE TITLE
Tracker might not be initialized

### ISSUE THREAD

**Issue by markgibbons25** [bartverdonck/Sitecore-Forms-Extensions#51]
**Describe the bug**
Occasionally I have noticed that when some CD instances start up we start getting null reference exceptions on CurrentContactContactIdentierHandler - var contact = tracker.Contact;

It looks like the current singleton method will keep a possibly null tracker that failed to initialize.

**Comment by bartverdonck** [comment]
Hi Mark,

Thanks for the update. I'm not releasing anymore updates to 1.x release for Sitecore 9.0.x.

However, I have also merged your commit into the master branch containing version 2.x for Sitecore 9.1+

Best Regards,

Bart
