### ISSUE TITLE
SXA

### ISSUE THREAD

**Issue by ben-norman-codehouse** [bartverdonck/Sitecore-Forms-Extensions#53]
The js files are located in sitecore modules/Web/ExperienceForms/scripts
For example, /sitecore%20modules/Web/ExperienceForms/scripts/jquery-2.1.3.min.js
When I put a form with Google Recaptcha on the form for example, the js files are redirected to a login screen. Should I add them to the theme and let them participate in Creative Exchange interactions or do I have to work out how to allow the files to be served from that location without being redirected to login.

**Comment by bartverdonck** [comment]
Hi Ben,

Normally no additional actions should by taken to get the module running with SXA.

I assume their is something security related in your project prohibiting access to the javascript.

Sorry I can't help you further.

Best Regards,

Bart
