### ISSUE TITLE
[Sitecore 9.0.2][Hidden Field] Default Value field is not saving the values

### ISSUE THREAD

**Issue by prabhatsharmafr** [bartverdonck/Sitecore-Forms-Extensions#55]
I am using `Sitecore 9.0.2 (rev. 180604)`  and installed `Sitecore Forms Extension 1.8` (which is compatible with Sitecore 9.0.x). Whenever I tried to add any value in the `default value` field of `Hidden Field` and save the form, it is flushing the value.

I saw that @rolek made the changes for it (only for Sitecore 9.1.x in version 2.2). 
![image](https://user-images.githubusercontent.com/49239328/64113654-2bc52780-cd8b-11e9-8030-1041c0c72bba.png)
![image](https://user-images.githubusercontent.com/49239328/64111441-ff0e1180-cd84-11e9-9a81-60911fa8f46b.png)

**Comment by bartverdonck** [comment]
Hi,

Updates to 1.x for Sitecore 9.0.x have been suspended.

The source code is available if you want to make any changes.

Best Regards,

Bart
