### ISSUE TITLE
Sitecore Forms Extension SerializationException 500 Error

### ISSUE THREAD

**Issue by prabhatsharmafr** [bartverdonck/Sitecore-Forms-Extensions#58]
Working with:

- Sitecore.NET 9.0.2 (rev. 180604)
- SXA 1.7.1
- Azure Search
- Sitecore Forms Extension 9.0-1.8.2 (also installed `nodb` package on CD)

I have created a customized save action. The form is working fine in CM but while trying to submit the form in CD, it throws 500 Error.
![image](https://user-images.githubusercontent.com/49239328/65315169-ecbf1080-db97-11e9-943b-48616c209018.png)

**Comment by bartverdonck** [comment]
Updated version 1.8.3 has been made available for download.
