### ISSUE TITLE
In method SendEmailExtended() fixedAddressHandler is null

### ISSUE THREAD

**Issue by MokoPolo** [bartverdonck/Sitecore-Forms-Extensions#59]
Hello,

In method SendEmailExtended() fixedAddressHandler is null. How does this value get initialized? I may be missing something. Thanks in advance!

**Comment by bartverdonck** [comment]
Hi,

The module uses dependency injection to get an instance of FixedAddressContactIdentierHandler. It looks like DI is failing in your case.

Things you can do:

- Check /sitecore/admin/showConfig.aspx and search if Feature.FormsExtensions.FormsComponentConfigurator, Feature.FormsExtensions is present.
- Check /sitecore/admin/ShowServicesConfig.aspx, and look if the service is initiated
