### ISSUE TITLE
PropertyGridForm.js references SPEAK components not on the PropertyGridForm Layout

### ISSUE THREAD

**Issue by rehbellOne** [bartverdonck/Sitecore-Forms-Extensions#62]
**Issue**
When I click on a Form Field (Single-Line Text for example) in the Forms Editor, I get a spinner of death. I've reviewed the Console.log in chrome to find that "this.FieldBindingTokensDataSource" is undefined. I took a look at the PropertyGridForm in Sitecore Rocks and sure enough, there is nothing in the layout.

**Smug-Report**
So this was either caused by 
* PropertyGridForm missing SPEAK components from the layout because they were not included in the package ... by accident?
* 2.2.1 Install package not installing properly

**My Info**
I'm using Sitecore 9.1 Update 1. 

**Work Around**
The solution was to replace the JS provided by the module with the default OOTB PropertyGridForm.js from the Sitecore install package. Works fine now, but I get the OpenSans.css 404 issue, however, I can live with that.

Thank you.

**Comment by bartverdonck** [comment]
Hi,

I have retested the module by installing it on a fresh Sitecore 9.1.1. Everything works as it is supposed to. I assume something went wrong during installation. Please try to reinstall.

Regarding the OpenSans.css 404 issue, that's a known bug in Sitecore unrelated to the module.

Best Regards,
Bart
