### ISSUE TITLE
Form validation in combination with checkboxes

### ISSUE THREAD

**Issue by kverheire** [bartverdonck/Sitecore-Forms-Extensions#7]
**Describe the bug**
Form validation fails when combining a Checbox list and a file upload field into the same form

**To Reproduce**
1. Create a new form in Sitecore Forms
2. Add a checkbox list and mark it as mandatory (and add a simple submit button)
3. When added into a page and published the form functions perfectly.
4. Now add a fileUpload field into the same form and perform the same assertion on its functionality.
5. The form now no longer accepts a selected checkbox as a valid form status and does not submit anymore
6. An example can be found here: https://app-a-we-cd.azurewebsites.net/testing/simpleform

**Expected behavior**
Validation and behavior of the FileUpload should not interfere with other field types

**Comment by bartverdonck** [comment]
I was able to reproduce the issue.

**Comment by bartverdonck** [comment]
Error is cause by formsextensions.validate.js
$.validator.setDefaults({ ignore: "" });
this setting was done to validate the hidden fields of the captcha

**Comment by bartverdonck** [comment]
replaced line with
$.validator.setDefaults({ ignore: ":hidden:not(.fxt-captcha)" });
and added class="fxt-captcha" in ReCaptcha.cshtml

**Comment by bartverdonck** [comment]
Fixed in release 1.4.4
