### ISSUE TITLE
Sitecore Forms do not show an error when the Send Email Submit Action fails to send an email

### ISSUE THREAD

**Issue by jsalwen** [bartverdonck/Sitecore-Forms-Extensions#70]
**Describe the bug**
Sitecore Forms do not show an error when the **Send Email** Submit Action fails to send an email.

**To Reproduce**
1. Setup a From with Submit Action of **Send Email**
2. Update the EXM config with bad value to force an error, e.g., 
    ```
    <sitecore>
      <exm>
        <eds>
          <smtpSettings>
            <server>fake.server.nocom</server>
          </smtpSettings>
        </eds>
      </exm>
    </sitecore>
    ```
3. Click the Submit button

**Expected behavior**
The form will display an error at the top of the form: e.g, *Send email failed!*

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 79.0.3945.88

**Additional context**
I see the error in the log: Eds.log.yyyyMMdd.hhmmss.txt file, but the form does not show the error.

I create a class that extends `SendEmailExtended`, so I could step through the `Execute` method. It appears the `SendMail` call does not throw an exception, so `Execute` always returns `true`.

The Sitecore Forms needs `Execute` to return `false` in order to show the Form error message.

**Comment by jsalwen** [comment]
@bartverdonck if you point me in the right direction, I am happy to submit a PR to fix.

**Comment by jsalwen** [comment]
after digging a bit deeper, it appears the `SendAutomatedMessage` ([doco](https://doc.sitecore.com/developers/exm/90/email-experience-manager/en/the-email-experience-manager-client-api.html#UUID-239053b5-2b6f-61ff-8f19-cbc44e772d8f_N1546537770278)) does not throw an error, so there is not way of knowing. So there may not be a way to fix this.

**Comment by bartverdonck** [comment]
Hi, since the mails are send with EXM. This is being done asynchrounously to the submittion of the form. When the form is submittend the SendAutomatedMessage places a task to send an email on the EXM queue.
EXM does have a build in mechanism to retry sending the message when it failed.
So you should be okay.
