### ISSUE TITLE
Google Recaptcha not displaying

### ISSUE THREAD

**Issue by cv1998** [bartverdonck/Sitecore-Forms-Extensions#72]
Hi,
I use sitecore 9.1. I installed Sitecore Forms Extensions for Sitecore 9.1-2.3.1.zip.
recaptcha displays on the form designer, but not displaying on the web page.
On the web page, I see this html markup, but recaptcha is not displaying

<div id="fxb_1273ecdf-c045-48dc-8952-7d9ab07f556c_Fields_218e1b3e-1266-4bf5-9a4e-f51f114d60c2__CaptchaValue_wrapper"></div>
<input id="fxb_1273ecdf-c045-48dc-8952-7d9ab07f556c_Fields_218e1b3e-1266-4bf5-9a4e-f51f114d60c2__CaptchaValue" name="fxb.1273ecdf-c045-48dc-8952-7d9ab07f556c.Fields[218e1b3e-1266-4bf5-9a4e-f51f114d60c2].CaptchaValue" type="hidden" class="fxt-captcha" data-val-required="Please confirm you are not a robot." data-val="true" />
<span class="field-validation-valid" data-valmsg-for="fxb.1273ecdf-c045-48dc-8952-7d9ab07f556c.Fields[218e1b3e-1266-4bf5-9a4e-f51f114d60c2].CaptchaValue" data-valmsg-replace="true"></span>

<script type="text/javascript">
  var reCaptchaArray = reCaptchaArray || [];
  reCaptchaArray.push(
    function() {
      var _captchaInput = window.document.getElementById('fxb_1273ecdf-c045-48dc-8952-7d9ab07f556c_Fields_218e1b3e-1266-4bf5-9a4e-f51f114d60c2__CaptchaValue');
      window.grecaptcha.render('fxb_1273ecdf-c045-48dc-8952-7d9ab07f556c_Fields_218e1b3e-1266-4bf5-9a4e-f51f114d60c2__CaptchaValue_wrapper',
        {
          'sitekey': 'correct site key here',
          'callback': function(token) {
            _captchaInput.value = token;
          },
          'expired-callback': function(args) {
            _captchaInput.value = '';
          }
        });
    }
  );
</script>
  <script src="https://www.google.com/recaptcha/api.js?onload=loadReCaptchas&render=explicit&hl=en" async defer></script>
        <script type="text/javascript">
            (function () {
				 function initialForm($) {
				   var $formEl = $("form[data-sc-fxb='3b69d148-d541-401d-bf58-d6ab9c11e444']");
				   if ($formEl.length && typeof $formEl.init_fxbConditions === 'function') {
					   var options = {};
					   $formEl.init_fxbConditions(options);
				   }
				 }

			    window.addEventListener('load', function () {
				   initialForm(jQuery);
				});
			})();
        </script>
		
Thanks

**Comment by cv1998** [comment]
Sorry, here is the entire markup

<div id="fxb_1273ecdf-c045-48dc-8952-7d9ab07f556c_Fields_218e1b3e-1266-4bf5-9a4e-f51f114d60c2__CaptchaValue_wrapper"></div>
<input id="fxb_1273ecdf-c045-48dc-8952-7d9ab07f556c_Fields_218e1b3e-1266-4bf5-9a4e-f51f114d60c2__CaptchaValue" name="fxb.1273ecdf-c045-48dc-8952-7d9ab07f556c.Fields[218e1b3e-1266-4bf5-9a4e-f51f114d60c2].CaptchaValue" type="hidden" class="fxt-captcha" data-val-required="Please confirm you are not a robot." data-val="true" />
<span class="field-validation-valid" data-valmsg-for="fxb.1273ecdf-c045-48dc-8952-7d9ab07f556c.Fields[218e1b3e-1266-4bf5-9a4e-f51f114d60c2].CaptchaValue" data-valmsg-replace="true"></span>

<script type="text/javascript">
  var reCaptchaArray = reCaptchaArray || [];
  reCaptchaArray.push(
    function() {
      var _captchaInput = window.document.getElementById('fxb_1273ecdf-c045-48dc-8952-7d9ab07f556c_Fields_218e1b3e-1266-4bf5-9a4e-f51f114d60c2__CaptchaValue');
      window.grecaptcha.render('fxb_1273ecdf-c045-48dc-8952-7d9ab07f556c_Fields_218e1b3e-1266-4bf5-9a4e-f51f114d60c2__CaptchaValue_wrapper',
        {
          'sitekey': 'correct site key here',
          'callback': function(token) {
            _captchaInput.value = token;
          },
          'expired-callback': function(args) {
            _captchaInput.value = '';
          }
        });
    }
  );
</script>
  <script src="https://www.google.com/recaptcha/api.js?onload=loadReCaptchas&render=explicit&hl=en" async defer></script>
        <script type="text/javascript">
            (function () {
				 function initialForm($) {
				   var $formEl = $("form[data-sc-fxb='3b69d148-d541-401d-bf58-d6ab9c11e444']");
				   if ($formEl.length && typeof $formEl.init_fxbConditions === 'function') {
					   var options = {};
					   $formEl.init_fxbConditions(options);
				   }
				 }

			    window.addEventListener('load', function () {
				   initialForm(jQuery);
				});
			})();
        </script>

**Comment by cv1998** [comment]
Sorry, here is the entire markup

```
<div id="fxb_1273ecdf-c045-48dc-8952-7d9ab07f556c_Fields_218e1b3e-1266-4bf5-9a4e-f51f114d60c2__CaptchaValue_wrapper"></div>
<input id="fxb_1273ecdf-c045-48dc-8952-7d9ab07f556c_Fields_218e1b3e-1266-4bf5-9a4e-f51f114d60c2__CaptchaValue" name="fxb.1273ecdf-c045-48dc-8952-7d9ab07f556c.Fields[218e1b3e-1266-4bf5-9a4e-f51f114d60c2].CaptchaValue" type="hidden" class="fxt-captcha" data-val-required="Please confirm you are not a robot." data-val="true" />
<span class="field-validation-valid" data-valmsg-for="fxb.1273ecdf-c045-48dc-8952-7d9ab07f556c.Fields[218e1b3e-1266-4bf5-9a4e-f51f114d60c2].CaptchaValue" data-valmsg-replace="true"></span>

<script type="text/javascript">
  var reCaptchaArray = reCaptchaArray || [];
  reCaptchaArray.push(
    function() {
      var _captchaInput = window.document.getElementById('fxb_1273ecdf-c045-48dc-8952-7d9ab07f556c_Fields_218e1b3e-1266-4bf5-9a4e-f51f114d60c2__CaptchaValue');
      window.grecaptcha.render('fxb_1273ecdf-c045-48dc-8952-7d9ab07f556c_Fields_218e1b3e-1266-4bf5-9a4e-f51f114d60c2__CaptchaValue_wrapper',
        {
          'sitekey': 'correct site key here',
          'callback': function(token) {
            _captchaInput.value = token;
          },
          'expired-callback': function(args) {
            _captchaInput.value = '';
          }
        });
    }
  );
</script>
  <script src="https://www.google.com/recaptcha/api.js?onload=loadReCaptchas&render=explicit&hl=en" async defer></script>
        <script type="text/javascript">
            (function () {
				 function initialForm($) {
				   var $formEl = $("form[data-sc-fxb='3b69d148-d541-401d-bf58-d6ab9c11e444']");
				   if ($formEl.length && typeof $formEl.init_fxbConditions === 'function') {
					   var options = {};
					   $formEl.init_fxbConditions(options);
				   }
				 }

			    window.addEventListener('load', function () {
				   initialForm(jQuery);
				});
			})();
        </script>
```
		
Thanks

**Comment by cv1998** [comment]
in the console, there is this warning

reCAPTCHA couldn't find user-provided function: loadReCaptchas on this file
https://www.gstatic.com/recaptcha/releases/eQmzkx3d5dtuXlLOA4pEID3I/recaptcha__en.js

**Comment by cv1998** [comment]
Hi Bart,
I found the issue. formsextensions.validate.js is not loaded.
It works now.

Thanks

**Comment by bartverdonck** [comment]
Glad you have found it.

Best Regards

**Comment by clauabad** [comment]
Sorry, what did you do? How to load  formsextensions.validate.js ? Thanks!
