### ISSUE TITLE
Recaptcha for multiple domains

### ISSUE THREAD

**Issue by cv1998** [bartverdonck/Sitecore-Forms-Extensions#73]
Hi Bart,
Can I use the Recaptcha in 2 separate web sites in the same Sitecore instance but having different domain (ie abc.com and xyz.com)?

Thanks

**Comment by bartverdonck** [comment]
Sure, as long as you use the same captcha account with the same public/private key.
You can configure the same account to be valid on multiple domains in google captcha console.
![image](https://user-images.githubusercontent.com/5012835/72386331-7edbbd80-3721-11ea-9fb9-5c11462acb3e.png)
