### ISSUE TITLE
Multi Page Form: Cannot read property 'unobtrusive' of undefined

### ISSUE THREAD

**Issue by elivnjak** [bartverdonck/Sitecore-Forms-Extensions#78]
In a multi page form, when i click the next button, the form loads page two but the client side validation no longer works. Clicking submit button submits the page and server side validation shows.

The console error that pops up when page two is loaded is:

`VM11233:3 Uncaught TypeError: Cannot read property 'unobtrusive' of undefined
    at HTMLFormElement.eval (eval at a (jquery.unobtrusive-ajax.min.js:formatted:21), <anonymous>:3:13)`

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 80.0.3987.100

**Additional context**
Using Sitecore 9.2

**Comment by bartverdonck** [comment]
Could not reproduce.
