### ISSUE TITLE
AssemblyInfo.cs does not have any AssemblyVersion attributes

### ISSUE THREAD

**Issue by markgibbons25** [bartverdonck/Sitecore-Forms-Extensions#79]
This seems to be resulting in a version of 0.0.0.0 which makes it a little hard to tell what version of the DLL we have on the system.

**Comment by bartverdonck** [comment]
Thanks for the note Mark. Will add it in next version.

**Comment by bartverdonck** [comment]
Started release guide (Release.md) and added this into the steps.
