### ISSUE TITLE
Add Media Library Support to File Upload

### ISSUE THREAD

**Issue by bartverdonck** [bartverdonck/Sitecore-Forms-Extensions#8]
Rework media library support to move some config into sitecore for more flexibility and add support on media library.

**Comment by dionis-sage** [comment]
Hi Bart,

At the moment I need to do file upload to media library, can you tell me how to do customization for that? I have seen your blog http://onelittlespark.bartverdonck.be/file-upload-for-sitecore-forms/ but I need more details about that. 

Thanks

**Comment by bartverdonck** [comment]
Hi,

The library will include media library support in the next version. I'm hoping on releasing that before the symposium.

Meanwhile, if you want to create your own medialib support, you can implement the IFileUploadStorageProvider interface. It receives a HttpPostedFileBase as input (containing the file stream), you need to return a class of the type IStoredFile (containing name and url).

You need to register your implementation in the config
 <fileUploadStorageProvider type="<<your-custom implementation>>" />

Best Regards,
Bart

**Comment by dionis-sage** [comment]
Thanks,

Can you tell me if I can control where to store uploaded file depending on form where it was uploaded? For example if I uploaded file in 'test' form I want to add it in media library 'test' folder.

**Comment by bartverdonck** [comment]
You would have to adapt the speak interface of the file upload control in order for the user to select a folder.

**Comment by bartverdonck** [comment]
Due to the following reasons, this feature will be abandoned and not included in the module.

- On CD servers there is no connection to the master database
- Adding the file over a service to the CM on master database would add an extra dependency, liability in the code and the functionality would not work when CM goes down.
- We would need to keep publishing of those items created on the master database in mind
- There could be timing issues when trying to add the uploaded file as attachment in mail via exm executed on email delivery server (also CM or a dedicated)
