### ISSUE TITLE
file upload throws an item with same name already exists

### ISSUE THREAD

**Issue by shobhatenkayilu** [bartverdonck/Sitecore-Forms-Extensions#82]
I have used the mdule to have file y=upload field

the file upload field is not mandatory
when I don't add any value to file upload it submits form successfully.

when any pdf,png etc is selected from file upload field the form wont submit
I get form buider error
when review stack trace
"item with same name already exists"

**Comment by bartverdonck** [comment]
Hi, 

Please provide version of the module + version of Sitecore.

Best Regards,

Bart

**Comment by bartverdonck** [comment]
Didn't get response from reporter.
