### ISSUE TITLE
Can't select hidden fields in the UrlParemetersEditor (as found on the Redirect to URL Submit Action)

### ISSUE THREAD

**Issue by joshuwa** [bartverdonck/Sitecore-Forms-Extensions#83]
I am seeing an issue where I can't select field types of HiddenField to map in the UrlParametersEditor dialog 

1. Add a hidden field
2. Add a Submit Button
3. Add a Redirect to URL Submit Action
4. Add a Parameter
5. In the Form Field select the Drop Down list of form fields
6. The HiddenField won't be available for mapping

**Expected behavior**
The HiddenField on the form should be in the list of Form Fields to map.

**Comment by bartverdonck** [comment]
Added the hiddenfield to the list on the urlparametereditor.
