### ISSUE TITLE
File Uploads not working

### ISSUE THREAD

**Issue by jsalwen** [bartverdonck/Sitecore-Forms-Extensions#84]
**Upload Files not uploading or Attaching to email**
I installed the package and updated `fileUploadStorageProvider` settings for `FileSystemFileUploadStorageProvider`. But File Uploads are not working

**To Reproduce**
1. Create a new Form
2. Add `File Upload` field to form
3. Add `Submit button` to form
4. Add `Send Email` submit action to button
5. Associate the `File Upload` field in the submit action
6. Publish form and email
7. View form
8. Add file and click button

**Expected behavior**
Receive the email with the file attached to the email

**Actual behavior**
Received the email, but the file is not attached. The file is also not in the folder specified in the `rootStoragePath`

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Version 81.0.4044.138 

**Sitecore Version:**
Sitecore: 9.1.1
Sitecore Forms Extensions for Sitecore 9.1-2.2

**Comment by bartverdonck** [comment]
Hi,

You might try these suggestions:

1) Can you check if the file is within the limits of the web.config settings?

<configuration>
  <system.web>
    <httpRuntime maxRequestLength="xxx" />
  </system.web>
</configuration>

2) Do you spot any javascript errors in the browser or code errors in the sitecore logs? Please provide them.

Best Regards,

Bart
