### ISSUE TITLE
Testing email submit action on CM server does not work

### ISSUE THREAD

**Issue by markgibbons25** [bartverdonck/Sitecore-Forms-Extensions#85]
Not a big issue, but a gotcha, is that on CM you can't use IClientApiService. 
https://doc.sitecore.com/developers/exm/93/email-experience-manager/en/sending-email-campaigns-programmatically.html

We were scratching our heads for a long time trying to test our forms. IClientApiService resolves as `null` on CM.
Would be good to have it be able to differentiate somehow.
Perhaps check for null and use the message bus api in that case?
This applies to all 9.x versions I believe.
Cheers.

**Comment by bartverdonck** [comment]
Hi Mark,

I was aware of the unavailability of the IClientApiService. Thanks for pointing to the article, this could provide a solution.

Br,

Bart

**Comment by bartverdonck** [comment]
Added fallback to automatedmessagesbus
