### ISSUE TITLE
Unable to use ValueProviders on Radio Button List Field

### ISSUE THREAD

**Issue by SchelstraeteRuben** [bartverdonck/Sitecore-Forms-Extensions#88]
Hi, we noticed that we received an error when using a valueprovider on a radio button list field. For example the Gender valueprovider included in this module.

The exception that occurs:

> Exception: System.ArgumentNullException
> 
> Message: Value cannot be null.
> 
> Parameter name: source
> 
> Source: System.Core
> 
>    at System.Linq.Enumerable.Contains[TSource](IEnumerable`1 source, TSource value, IEqualityComparer`1 comparer)
> 
>    at Sitecore.ExperienceForms.Mvc.Models.Fields.ListViewModel.<>c__DisplayClass31_0.<OnValueChanged>b__0(ListFieldItem i)
> 
>    at System.Collections.Generic.List`1.ForEach(Action`1 action)
> 
>    at Sitecore.ExperienceForms.Mvc.Models.Fields.InputViewModel`1.InitializeValue(FieldValueProviderContext context)
> 
>    at Sitecore.ExperienceForms.Mvc.Pipelines.GetModel.CreateModel.Process(GetModelEventArgs args)
> 
>    at (Object , Object )
> 

I reported this to Sitecore Support, assuming that it was a bug in Sitecore, but this is the response i received:

> I was able to reproduce the issue using your “XDbGenderFieldValueBinder” value provider.
> 
> It occurs because your “Feature.FormsExtensions.ValueProviders.xDbFieldValueBinders.BaseXDbFieldValueBinder<T>.GetValue” method returns the “string” object instead of the expected “List<string>” object for a list field.
> 
> Please rewrite this method, for example, as follows:
> 
> public override object GetValue(string parameters)
> 
> {
> 
>   if (!ValueProviderConditionsContext.ValueProviderConditionsMet)
> 
>   {
> 
>     return new List<string>() { string.Empty };
> 
>   }
> 
>   IFieldValueBinderResult bindingValue = GetBindingValue();
> 
>   if (!bindingValue.HasValue())
> 
>   {
> 
>     return new List<string>() { string.Empty };
> 
>   }
> 
>   return new List<string>() { bindingValue.Value.ToString() };
> 
> }

**Comment by bartverdonck** [comment]
Hi Ruben,

I'm aware of this issue https://github.com/bartverdonck/Sitecore-Forms-Extensions/issues/80 . 

I have also written a blog post on this.
http://onelittlespark.bartverdonck.be/value-provider-on-list-components/

The problem I'm facing is that the value providers are independent of the component they are used on. I need to find a way to know in the valueprovider if the component expects a list or a string.

Best Regards,

Bart
