### ISSUE TITLE
"Please confirm you are not a robot"

### ISSUE THREAD

**Issue by druhela** [bartverdonck/Sitecore-Forms-Extensions#95]
Hi

I am using recaptcha field in one of the form. But I am getting error "Please confirm you are not a robot" after form submission. There is no error in console to get the exact problem. Also this is happening when using "Show Form Page", if using "Redirect to Page" form is getting submitted successfully. 
<img width="273" alt="recaptcha" src="https://user-images.githubusercontent.com/28951074/97774234-21174580-1b7c-11eb-88bb-990fea9d8d7a.png">

**Comment by bartverdonck** [comment]
Closing the issue due to innactivity
