### ISSUE TITLE
Feature request - submit action - subscribe to preference

### ISSUE THREAD

**Issue by markgibbons25** [bartverdonck/Sitecore-Forms-Extensions#97]
An underutilized feature in Sitecore is the Preference Centre, and I think this is because some features such as a submit action to subscribe to preferences are missing. It seems like this should be part of the platform, but it's not ;)

Drawing inspiration from the built-in segmentation rule:

> where the contact _has (not)_ subscribed to marketing preference _marketing preference_ for the manager root _manager root_

Perhaps we could have something similar on a submit action where we can select a manager root and then one or more preferences to subscribe to?

**Comment by monkey-dsc** [comment]
@bartverdonck  maybe we should have a joint venture on this one ;) See: https://github.com/monkey-dsc/Feature.SitecoreForms.MarketingCategoriesSubscription/

**Comment by bartverdonck** [comment]
To be honest, I forgot about that feature myself. Haven't used it yet, and didn't really feel the need. Since @monkey-dsc  has already an excellent separate module on this, I feel no immediate need to add it to SFE.

**Comment by bartverdonck** [comment]
@monkey-dsc I'm not that familiar with the preference center and the impact it would have. At a first glance on your install notes, I see that the message bus is required for cm/cd communication. This results in a different install procedure. I would have to investigate the impact on containered module delivery. To keep things simple in SFE, my initial thoughts are to keep the modules separate.

**Comment by bartverdonck** [comment]
Closing for now.
