### ISSUE TITLE
Feature request - value provider for preference centre preferences

### ISSUE THREAD

**Issue by markgibbons25** [bartverdonck/Sitecore-Forms-Extensions#98]
Raising this separately from #97 as we may not actually need both functions but up for discussion.

Perhaps we could have a value provider where we could bind a checkbox field to a particular preference in the preference centre so that updates to it are saved, and on page load the current value is prepopulated.

**Comment by bartverdonck** [comment]
Looks a bit more lightweight then #97 
I will keep it on the backlog, but it' not my biggest priority.

Best Regards,
